
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdskduyrckyupeyhcyyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkc2tkdXlyY2t5dXBleWhjeXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDY0MjEsImV4cCI6MjA2NDUyMjQyMX0.yWXv3FEm6eLPTDqGDhJk9HlpL1SzWuJSZmF6f--9XKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
